#!/bin/bash
# ============================================================
# [PostToolUse Hook] CWM Change Logger
# ============================================================
# 변경 내역을 .cwm/docs/logs/change-log.md에 자동 기록.
# stdout 없음 — 컨텍스트 오염 방지.
# ============================================================

INPUT=$(cat)

command -v jq &>/dev/null || exit 0

TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // empty')
CWD=$(echo "$INPUT" | jq -r '.cwd // "."')
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

LOG_DIR="$CWD/.cwm/docs/logs"
LOG_FILE="$LOG_DIR/change-log.md"

mkdir -p "$LOG_DIR"

# 로그 파일 초기화
if [ ! -f "$LOG_FILE" ]; then
  cat > "$LOG_FILE" <<'HEADER'
# Change Log

> Auto-generated by CWM change-logger hook.

| Time | Tool | File | Action |
|------|------|------|--------|
HEADER
fi

if [ "$TOOL_NAME" = "Edit" ]; then
  FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // "unknown"')
  OLD_STR=$(echo "$INPUT" | jq -r '.tool_input.old_string // ""' | head -c 60)
  echo "| $TIMESTAMP | Edit | \`$FILE_PATH\` | \`${OLD_STR}...\` |" >> "$LOG_FILE"

elif [ "$TOOL_NAME" = "Write" ]; then
  FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // "unknown"')
  echo "| $TIMESTAMP | Write | \`$FILE_PATH\` | file create/overwrite |" >> "$LOG_FILE"

elif [ "$TOOL_NAME" = "Bash" ]; then
  COMMAND=$(echo "$INPUT" | jq -r '.tool_input.command // ""')
  if echo "$COMMAND" | grep -qE '(mv |cp |rm |mkdir |chmod |npm install|pnpm |yarn |pip )'; then
    CMD_SHORT=$(echo "$COMMAND" | head -c 80)
    echo "| $TIMESTAMP | Bash | — | \`${CMD_SHORT}\` |" >> "$LOG_FILE"
  fi
fi

# stdout 없음 — 컨텍스트 오염 방지
exit 0
